In [2]:
import numpy as np

In [3]:
a = np.array([[0, 1, 2, 3, 4, 5],
              [3,1,2,4,1,3]])

a

array([[0, 1, 2, 3, 4, 5],
       [3, 1, 2, 4, 1, 3]])

In [4]:
a.ndim

2

In [5]:
a.shape

(2, 6)

In [6]:
b = a.reshape((3,4))
b

array([[0, 1, 2, 3],
       [4, 5, 3, 1],
       [2, 4, 1, 3]])

In [7]:
a[1][0] = 77
a

array([[ 0,  1,  2,  3,  4,  5],
       [77,  1,  2,  4,  1,  3]])

In [8]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5, 77,  1],
       [ 2,  4,  1,  3]])

In [9]:
c = a.reshape((3,4)).copy()
c[0][0] = -99

c

array([[-99,   1,   2,   3],
       [  4,   5,  77,   1],
       [  2,   4,   1,   3]])

In [10]:
d = np.array([1,2,3,4,5])
d**2

array([ 1,  4,  9, 16, 25])

In [14]:
a = np.array([0,1,2,3,4,5])
a[np.array([2,3,4])]

array([2, 3, 4])

In [15]:
a>4

array([False, False, False, False, False,  True])

In [20]:
a[a>4] = 4
a

a.clip(1,4)

array([1, 1, 2, 3, 4, 4])

In [26]:
p = np.array([1, 2, np.nan, 3, 4])
p


array([ 1.,  2., nan,  3.,  4.])

In [27]:
import timeit

normal_py_sec = timeit.timeit('sum(x*x for x in range(1000))',
                              number=10000)
naive_np_sec = timeit.timeit(
    'sum(na*na)',
    setup='import numpy as np; na = np.arange(1000)',
    number=10000)
good_np_sec = timeit.timeit(
    'na.dot(na)',
    setup="import numpy as np; na=np.arange(1000)",
    number=10000)

print("Noemal Python: %f sec" % normal_py_sec)
print("Naive Numbpy: %f sec" % naive_np_sec)
print("Good Numpy: %f sec" % good_np_sec)

Noemal Python: 0.796018 sec
Naive Numbpy: 0.664218 sec
Good Numpy: 0.014506 sec
